version: '3'

services:
  wake-on-lan-flask-svc:
    build:           # Build the container
      context: ./src
    environment:
      - SSH_AUTH_SOCK=/ssh-agent
    volumes:
      - $SSH_AUTH_SOCK:/ssh-agent
    ports:
      - "7777:5000"  # Map port 5000 from the container to port 7777 on the host
      # - "0.0.0.0:7777:5000"  # Map port 5000 from the container to port 7777 on the host
    restart: always  # Restart the container if it stops for any reason
    image: wake-on-lan-flask-svc:latest
    container_name: wake-on-lan-flask-svc

# https://github.com/hkupty/ssh-agent
# https://unix.stackexchange.com/questions/140075/ssh-add-is-not-persistent-between-reboots
