apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  labels:
    io.kompose.service: samba
  name: samba
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: samba
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      labels:
        io.kompose.service: samba
    spec:
      containers:
        - name: samba
          image: dperson/samba
          args: 
            - -p 
            - -u 
            - "$(SMB_USER);$(SMB_PASSWORD)"
            - -s 
            - "$(SMB_NAME);$(SMB_CONTAINER_PATH);yes;no;no;$(SMB_USER)"
          envFrom:
            - configMapRef:
                name: env
          ports:
            - containerPort: 445
          resources: 
            limits:
              cpu: 100m # the CPU limit is define in milicore (m)
              memory: 100Mi # the Memory is define in Mebibytes (Mi)
          stdin: true
          tty: true
      restartPolicy: Always
status: {}
