apiVersion: v1
kind: Service
metadata:
  namespace: samba
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  labels:
    io.kompose.service: samba
  name: samba
spec:
  ports:
    - name: "445"
      port: 445
      targetPort: 445
  selector:
    io.kompose.service: samba
status:
  loadBalancer: {}
