version: '3.7'

services:
  plex:
    image: lscr.io/linuxserver/plex
    container_name: plex
    network_mode: host
    environment:
      # OS
      TZ: 'America/Argentina/Buenos_Aires'
      PUID: 1000
      PGID: 1000
      VERSION: docker
      PLEX_CLAIM: ${PLEX_CLAIM}
    env_file:
      - '.env'
    volumes:
      - './plex/config:/config'
      - './plex/tvseries/:/tv'
      - './plex/movies:/movies'
    restart: unless-stopped
