version: '3.7'

services:
  transmission:
    image: lscr.io/linuxserver/transmission
    container_name: transmission
    environment:
      # OS
      TZ: 'America/Argentina/Buenos_Aires'
      PUID: 1000
      PGID: 1000
      # APP
      TRANSMISSION_WEB_HOME: /combustion-release/ #optional
    volumes:
      - './transmission:/config'
      - '${STORAGE}/torrents:/downloads'
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped

  plex:
    image: lscr.io/linuxserver/plex
    container_name: plex
    environment:
      # OS
      TZ: 'America/Argentina/Buenos_Aires'
      PUID: 1000
      PGID: 1000
      VERSION: docker
      PLEX_CLAIM: ${PLEX_CLAIM}
    env_file:
      - '.env'
    volumes:
      - './plex/config:/config'
      - './plex/tvseries/:/tv'
      - './plex/movies:/movies'
    depends_on:
      - transmission
    restart: unless-stopped
    networks: 
      lan:
        ipv4_address: 192.168.0.3

networks:
  lan:
    driver: macvlan
    driver_opts:
      parent: eth0
    ipam:
      config:
        - subnet: '192.168.0.0/24'
          gateway: '192.168.0.1'
