version: "3.7"

services:
  samba:
    container_name: samba
    image: dperson/samba
    command: '-p -u "${SMB_USER};${SMB_PASSWORD}" -s "${SMB_NAME};${SMB_CONTAINER_PATH};yes;no;no;${SMB_USER}"'
    env_file:
      - '.env'
    stdin_open: true
    tty: true
    ports:
      - 445:445
    volumes:
      # - '/usr/share/zoneinfo/America/Argentina/Buenos_Aires:/etc/localtime'
      - '/usr/share/zoneinfo/America/Santiago:/etc/localtime'
      - '${SMB_LOCAL_PATH}:${SMB_CONTAINER_PATH}'
    restart: always
