version: '3.7'

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    links:
      - unbound
    ports:
      - '53:53/tcp'
      - '53:53/udp'
      - '67:67/udp'
      - '80:80/tcp'
      - '443:443/tcp'
    environment:
      ServerIP: ${SERVER_IP}
      PIHOLE_DNS_: '10.0.0.2#5053;10.0.0.2#5053'
      DNSMASQ_LISTENING: 'all'
      TZ: 'America/Argentina/Buenos_Aires'
      PUID: 1000
      PGID: 1000
      WEBPASSWORD: ${WEB_PASSWORD}
      IPv6: 'false'
    env_file:
      - '.env'
    volumes:
      - './etc-pihole/:/etc/pihole/'
      - './etc-dnsmasq.d/:/etc/dnsmasq.d/'
    dns:
      - 127.0.0.1
      - 1.1.1.1
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    networks:
      pihole_net:
        ipv4_address: 10.0.0.3

  unbound:
    container_name: unbound
    image: klutchell/unbound:latest
    command:
      - '-v'
    ports:
      - '5053:5053/tcp'
      - '5053:5053/udp'
    volumes:
      - '/home/pi/raspberry-automation/docker/pi-hole/etc/unbound/:/etc/unbound/'
    healthcheck:
      test: ["CMD-SHELL", "drill -Qp 5053 nlnetlabs.nl @127.0.0.1"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 5s
    restart: unless-stopped
    networks:
      pihole_net:
        ipv4_address: 10.0.0.2

networks:
  pihole_net:
    ipam:
      config:
        - subnet: 10.0.0.0/29
