version: '3.7'

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - '53:53/tcp'
      - '53:53/udp'
      - '67:67/udp'
      - '80:80/tcp'
      - '443:443/tcp'
    environment:
      TZ: 'America/Argentina/Buenos_Aires'
      WEBPASSWORD: ${WEBPASSWORD}
      IPv6: 'false'
      PIHOLE_DNS_: '127.0.0.1#5335,127.0.0.1#5335'
    env_file:
      - '.env'
    volumes:
      - './etc-pihole/:/etc/pihole/'
      - './etc-dnsmasq.d/:/etc/dnsmasq.d/'
    dns:
      - 127.0.0.1
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    network_mode: host

  unbound:
    image: klutchell/unbound
    ports:
      - '5335:5335/tcp'
      - '5335:5335/udp'
    volumes:
      - '/home/pi/raspberry-automation/docker/pi-hole/etc/unbound/:/etc/unbound/'
    restart: unless-stopped

networks:
  containers:
    ipam:
      config:
        - subnet: 172.20.0.0/24
