---
version: '3.7'

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - '53:53/tcp'
      - '53:53/udp'
      - '80:80/tcp'
      - '443:443/tcp'
    environment:
      # OS
      TZ: 'America/Argentina/Buenos_Aires'
      PUID: 1000
      PGID: 1000
      # HTTP
      VIRTUAL_HOST: pi.hole
      ServerIP: ${SERVER_IP}
      WEBPASSWORD: ${WEB_PASSWORD}
      WEBTHEME: 'default-dark'
      # DNS
      PIHOLE_DNS_: '10.0.0.2#5053;10.0.0.2#5053'
      DNSMASQ_LISTENING: 'all'
      IPv6: 'false'
      # DHCP
      DHCP_ACTIVE: 'true'
      DHCP_START: 192.168.0.2
      DHCP_END: 192.168.0.254
      DHCP_ROUTER: 192.168.0.1
      DHCP_LEASETIME: 1
      PIHOLE_DOMAIN: pi-hole
      DHCP_IPv6: 'false'
      DHCP_rapid_commit: 'true'
    env_file:
      - '.env'
    volumes:
      - './etc/pihole/:/etc/pihole/'
      - './etc/dnsmasq.d/:/etc/dnsmasq.d/'
    dns:
      - 127.0.0.1
      - 1.1.1.1
    cap_add:
      - NET_ADMIN
    depends_on:
      - dhcphelper
      - unbound
    restart: unless-stopped
    networks:
      pihole_net:
        ipv4_address: 10.0.0.3

  unbound:
    container_name: unbound
    image: klutchell/unbound:latest
    ports:
      - '5053:5053/tcp'
      - '5053:5053/udp'
    restart: unless-stopped
    networks:
      pihole_net:
        ipv4_address: 10.0.0.2
      
  wireguard:
    container_name: wireguard
    image: linuxserver/wireguard
    ports:
      - '51820:51820/udp'
    environment:
      # OS
      PUID: 1000
      PGID: 1000
      TZ: 'America/Argentina/Buenos_Aires'
      # VPN
      SERVERPORT: 51820
      PEERS: 2
      PEERDNS: 'auto'
      INTERNAL_SUBNET: 10.13.13.0
      ALLOWEDIPS: '0.0.0.0/0, ::0/0'
    volumes:
      - '/root/wireguard:/config'
      - '/lib/modules:/lib/modules'
      - '/usr/src:/usr/src'
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    restart: unless-stopped
    networks:
      pihole_net:
        ipv4_address: 10.0.0.4

  dhcphelper:
    container_name: dhcp-helper
    build: ./dhcp-helper
    command: -s 10.0.0.3
    network_mode: 'host'
    cap_add:
      - NET_ADMIN
    restart: unless-stopped

networks:
  pihole_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/29
